---
title             : "Ambiguity in Category Learning and Stereotype Formation"
shorttitle        : "Ambiguity in Categories and Stereotypes"

author:
  - name          : "Lenard Dome"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Cognition Institute, School of Psychology, Plymouth University"
    email         : "lenarddome@protonmail.ch"
affiliation       :
  - id            : "1"
institution   : "Plymouth University"

authornote: |
  This proposal was submitted to ESRC funded studentship in 2019.

abstract: |
        My main intention is to do an effect centric research on ambiguity
        in categorization and social categorization.

        I would like to standradize how these effects are
        reproduced by establishing several constraint which would need to be
        satisfied in order to reproduce and replicate a phenomena - which will
        be fitted to formal models.

keywords          : "category learning, ambiguity, formal models, stereotype formation, benchmark phenomena"
wordcount         : "X"

bibliography      : ["lib.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
header-includes:
  - \usepackage{setspace}
  - \doublespacing
---

```{r setup, include = FALSE}
library("papaja")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

\newpage

# References
```{r create_r-references}
r_refs(file = "lib.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
